name: 'Jira release GitHub action for monorepo'
description: 'GitHub action that creates a Jira and Github release whenever a tag is pushed'
author: 'Parro<parrok@gmail.com>'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'truck'
  color: 'orange'

# Define your inputs here.
inputs:
  jira_project_domain:
    description: 'Jira project domain'
    required: true
  jira_project_id:
    description: 'Jira project id'
    required: true
  jira_project_key:
    description: 'Jira issue key prefix'
    required: true

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
