@ISSUE_KEY=AT-6

PUT https://parrok.atlassian.net/rest/api/3/issue/{{ISSUE_KEY}}
Authorization: Basic {{ATLASSIAN_API_TOKEN}}
Content-Type: application/json
{
    "update": {
      "fixVersions": [
        { 
          "add": {
             "id": "10068"
          }
        }
      ]
    }
  }